### ISSUE TITLE
update httomo stadard loader template

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomo-backends#34]
to be able to auto generate pipelines the standard tomo loader template will be updated to 
```
- method: standard_tomo
  module_path: httomo.data.hdf.loaders
  parameters:
    data_path: entry1/tomo_entry/data/data
    image_key_path: entry1/tomo_entry/instrument/detector/image_key
    rotation_angles:
      data_path: /entry1/tomo_entry/data/rotation_angle
    preview:
      detector_x: # horizontal data previewing/cropping
        start:
        stop:
      detector_y: # vertical data previewing/cropping
        start:
        stop:
```
